### ISSUE TITLE
GitLab Pages & .gitlab-ci.yml

### ISSUE THREAD

**Issue by anthonyjdella** [coreui/coreui-free-react-admin-template#171]
I'm trying to deploy my app to GitLab Pages which is like GitHub pages.

I'm having issues with the CI pipeline, it is failing.
```
npm ERR! Failed at the @coreui/coreui-free-react-app-admin-template@2.1.6 build script.
```

My .gitlab-ci.yml is like this:

```
image: node: latest

pages:
    stage: deploy
    script:
        - npm install
        - npm run build
        - rm -rf public
        - mv build public
    artifacts:
        paths:
            -public
```

Within my package.json, I have added a home page property:

```
"homepage": "https://username.gitlab.org/nameofmyrepo"
```

Any help is appreciated. Thanks
